
project_id = "uyjryuopuqgmsvayiccl"

[api]
enabled = true

[functions.manage-client-profile]
verify_jwt = true

[functions.set-invitation-token]
verify_jwt = false

[functions.send-proposal-invitation]
verify_jwt = true

[functions.health-check]
verify_jwt = false

[functions.google-places-autocomplete]
verify_jwt = false

[functions.google-place-details]
verify_jwt = false
