
project_id = "uyjryuopuqgmsvayiccl"

[api]
enabled = true

[functions.accept-proposal]
verify_jwt = false

[functions.manage-client-profile]
verify_jwt = true

[functions.set-invitation-token]
verify_jwt = false

[functions.send-proposal-invitation]
verify_jwt = true

[functions.health-check]
verify_jwt = false

[functions.google-places-autocomplete]
verify_jwt = false

[functions.google-place-details]
verify_jwt = false

[functions.google-maps-health-check]
verify_jwt = false

[functions.generate-proposal-pdf]
verify_jwt = true

[functions.bulk-upload-proposals]
verify_jwt = true
