import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { DashboardHeader } from "@/components/dashboard/DashboardHeader";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { ArrowRight, CheckCircle2, AlertTriangle } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { PortfolioHero } from "@/components/dashboard/v2/PortfolioHero";
import { NetworkHealth } from "@/components/dashboard/v2/NetworkHealth";
import { useSuperPartnerNetwork } from "@/hooks/dashboard/useSuperPartnerNetwork";
import { useReducedMotion } from "@/hooks/useReducedMotion";

interface Stats {
  total_agents: number;
  aggregated_mwp: number;
  current_rate: number;
  pending_commission: number;
  paid_commission: number;
}

const fmtZar = (n: number) =>
  new Intl.NumberFormat("en-ZA", {
    style: "currency",
    currency: "ZAR",
    maximumFractionDigits: 0,
  }).format(n || 0);

const fmtMwp = (n: number) => `${n.toFixed(2)} MWp`;

export default function SuperPartnerDashboard() {
  const [stats, setStats] = useState<Stats | null>(null);
  const [loadingStats, setLoadingStats] = useState(true);
  const reduced = useReducedMotion();
  const { data: network, isLoading: loadingNetwork } = useSuperPartnerNetwork();

  useEffect(() => {
    (async () => {
      const { data, error } = await supabase.rpc("get_super_partner_dashboard_stats");
      if (!error && data && (data as any[]).length > 0) {
        setStats((data as any[])[0] as Stats);
      }
      setLoadingStats(false);
    })();
  }, []);

  const companies = network?.companies ?? [];

  /** Interventions — defined rules over real link dates and signed MWp. */
  const interventions = useMemo(() => {
    const needsAttention = companies.filter((c) => c.segment === "needs_attention");
    const notActivated = companies.filter((c) => c.segment === "not_activated");
    const out: { id: string; what: string; why: string }[] = [];

    if (needsAttention.length > 0) {
      out.push({
        id: "stalled",
        what: `${needsAttention.length} partner${needsAttention.length === 1 ? "" : "s"} linked over a month with no signed MWp`,
        why: needsAttention
          .slice(0, 3)
          .map((c) => c.company_name)
          .join(", "),
      });
    }
    if (notActivated.length > 0) {
      out.push({
        id: "new",
        what: `${notActivated.length} recently linked partner${notActivated.length === 1 ? "" : "s"} yet to sign their first project`,
        why: notActivated
          .slice(0, 3)
          .map((c) => c.company_name)
          .join(", "),
      });
    }
    return out;
  }, [companies]);

  const loading = loadingStats || loadingNetwork;

  return (
    <DashboardLayout requiredRole="super_partner">
      <DashboardHeader
        title="Super Partner Dashboard"
        description="How your partner network is performing, and where to intervene."
      />

      {loading ? (
        <div className="space-y-6">
          <Skeleton className="h-40 w-full rounded-xl" />
          <Skeleton className="h-40 w-full rounded-lg" />
        </div>
      ) : (
        <>
          <PortfolioHero
            label="Network portfolio"
            mwp={Number(stats?.aggregated_mwp ?? 0)}
            caption="Signed MWp generated by the partners in your network."
            figures={[
              {
                label: "Partner companies",
                value: String(companies.length),
                numericValue: companies.length,
              },
              {
                label: "Producing partners",
                value: String(
                  companies.filter((c) => c.segment === "producing").length
                ),
                numericValue: companies.filter((c) => c.segment === "producing").length,
              },
              {
                label: "Linked partners",
                value: String(stats?.total_agents ?? 0),
                numericValue: stats?.total_agents ?? 0,
              },
              {
                label: "Your rate",
                value: stats?.current_rate != null ? `${stats.current_rate}%` : "Not set",
              },
            ]}
          />

          <NetworkHealth companies={companies} loading={loadingNetwork} />

          <motion.div
            initial={reduced ? false : { opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3, delay: reduced ? 0 : 0.08 }}
          >
            <Card className="mb-6 border-crunch-yellow/50">
              <CardHeader className="pb-3">
                <CardTitle className="text-lg flex items-center gap-2">
                  <AlertTriangle className="h-4 w-4 text-crunch-yellow" />
                  Where to intervene
                </CardTitle>
                <p className="text-xs text-muted-foreground mt-1">
                  Based on real link dates and signed MWp — no estimated scores.
                </p>
              </CardHeader>
              <CardContent className="pt-0">
                {interventions.length === 0 ? (
                  <div className="flex items-start gap-3 py-2">
                    <CheckCircle2 className="mt-0.5 h-5 w-5 text-[#8ED973]" />
                    <div>
                      <p className="font-medium">Every partner is producing</p>
                      <p className="text-sm text-muted-foreground">
                        No dormant or unactivated partners in your network.
                      </p>
                    </div>
                  </div>
                ) : (
                  <ul className="divide-y">
                    {interventions.map((item) => (
                      <li
                        key={item.id}
                        className="flex flex-wrap items-center justify-between gap-3 py-3 first:pt-0"
                      >
                        <div className="min-w-0">
                          <p className="font-medium">{item.what}</p>
                          <p className="mt-0.5 text-xs text-muted-foreground truncate">
                            {item.why}
                          </p>
                        </div>
                        <Button asChild size="sm" variant="outline">
                          <Link to="/super-partner/my-companies">
                            Open partners
                            <ArrowRight className="ml-1 h-3.5 w-3.5" />
                          </Link>
                        </Button>
                      </li>
                    ))}
                  </ul>
                )}
              </CardContent>
            </Card>
          </motion.div>

          <Card className="mb-8">
            <CardHeader className="pb-3">
              <CardTitle className="text-base">Commission</CardTitle>
            </CardHeader>
            <CardContent className="pt-0 flex flex-wrap items-end gap-8">
              <div>
                <p className="text-xs text-muted-foreground">Pending</p>
                <p className="text-xl font-semibold">
                  {fmtZar(Number(stats?.pending_commission ?? 0))}
                </p>
              </div>
              <div>
                <p className="text-xs text-muted-foreground">Paid</p>
                <p className="text-xl font-semibold">
                  {fmtZar(Number(stats?.paid_commission ?? 0))}
                </p>
              </div>
              <div>
                <p className="text-xs text-muted-foreground">Network signed</p>
                <p className="text-xl font-semibold">
                  {fmtMwp(Number(stats?.aggregated_mwp ?? 0))}
                </p>
              </div>
              <Button asChild variant="outline" size="sm" className="ml-auto">
                <Link to="/super-partner/commission">
                  Commission ledger
                  <ArrowRight className="ml-1.5 h-4 w-4" />
                </Link>
              </Button>
            </CardContent>
          </Card>
        </>
      )}
    </DashboardLayout>
  );
}
