import { SafeMotionDiv } from "@/components/common/SafeMotionDiv";
import { motion } from "framer-motion";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
  {
    question: "What is carbon?",
    answer: "Carbon is generated through things like the smoke from your car exhaust, at manufacturing factories or coal burning to make electricity. The dirty haze hanging over your town, that is likely carbon. Too much carbon makes the air dirty and polluted and can hurt us and our planet. We want to offset, or balance out this carbon and help keep the Earth clean and healthy.",
  },
  {
    question: "What are carbon credits and how do you earn them?",
    answer: "Carbon credits are like 'gold stars' you earn for making and more importantly using clean green energy from your solar system. The more clean energy you make and use, the more carbon credits you earn and help to keep our air clean and fresh.",
  },
  {
    question: "How does my home solar system help offset carbon?",
    answer: "Your installed solar system helps offset carbon by generating clean green energy from the sun and then using it in your home to power light bulbs, television, wifi and other electrical appliances. This means you use green energy rather than electricity from sources that make the air dirty, like energy which was generated by burning coal. And that is how you help offset and prevent tons of carbon being released into the air.",
  },
  {
    question: "Tell me how I get rewarded for my carbon offset?",
    answer: "By joining our Crunch Carbon programme, you unlock additional value from the solar energy you're already producing and using. We aggregate all the solar systems togther and then create carbon credits. During this process we manage the full verification and audit process, and sale of the credits on your behalf. The proceeds are then shared with you typically in the form of solar related services if you choose or cash back into your pocket. Simply put, you're rewarded for using solar. Simple.",
  },
  {
    question: "The nuts and bolts of how it works?",
    answer: "Homeowners who own their solar systems can join the program. Crunch Carbon, with your permission through a signed agreement, drives the carbon credit generation process. We collect data about your solar system (capacity, specifications, location, costs) and energy generated. With many other homeowners, estates and complexes, we put all these carbon offsets together. Crunch Carbon handles the collection, processing, audit and verification of the solar energy usage data. Once verified, we sell these carbon credits and reward the owners through services offered.",
  },
  {
    question: "But do I qualify for the program?",
    answer: "There are five main qualifying criteria: (1) You must be the legal owner of the solar system or plant. (2) The system must be within South Africa. (3) The system must be smaller than 15MWp (Megawatts peak). (4) The system may not be participating in any other GHG programs. (5) The system must have been commissioned on or after 15 September 2022. No. 5 is the most important - sadly we cannot help if the system was commissioned before that date.",
  },
  {
    question: "Who is Crunch Carbon the company?",
    answer: "We are a partnership recognised in the field of carbon emissions management, and adhere to industry principles and standards. We have a team of experts and specialist associates that brings together a diverse range of experience and skills, united by a passion for sustainability and a commitment to excellence. With a focus on transparency, integrity, and forward-thinking solutions, we are positioned at the forefront of driving positive environmental change.",
  },
];

export const WhyChooseUsFAQ = () => {
  return (
    <section className="py-16 md:py-24 bg-gradient-to-br from-crunch-yellow/5 to-white">
      <div className="container mx-auto px-4 max-w-4xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-center space-y-4 mb-12"
        >
          <h2 className="text-3xl md:text-4xl font-bold text-crunch-black">
            Frequently Asked Questions
          </h2>
          <p className="text-lg text-crunch-black/70">
            Here are some common questions about Crunch Carbon and how carbon credits work
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.2 }}
        >
          <Accordion type="single" collapsible className="space-y-4">
            {faqs.map((faq, index) => (
              <AccordionItem
                key={index}
                value={`item-${index}`}
                className="bg-white rounded-xl border border-crunch-black/5 px-6 shadow-sm hover:shadow-md transition-shadow"
              >
                <AccordionTrigger className="text-left hover:text-crunch-yellow transition-colors py-4">
                  <span className="font-semibold text-crunch-black pr-4">
                    {faq.question}
                  </span>
                </AccordionTrigger>
                <AccordionContent className="text-crunch-black/70 pb-4">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </motion.div>
      </div>
    </section>
  );
};
