import { useEffect, useRef, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { CheckCircle2 } from "lucide-react";

interface TermsAndConditionsSectionProps {
  onScrolledToBottom: () => void;
}

export function TermsAndConditionsSection({ onScrolledToBottom }: TermsAndConditionsSectionProps) {
  const [hasReachedBottom, setHasReachedBottom] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);
  const sentinelRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting && !hasReachedBottom) {
          setHasReachedBottom(true);
          onScrolledToBottom();
        }
      },
      { threshold: 1.0 }
    );

    if (sentinelRef.current) {
      observer.observe(sentinelRef.current);
    }

    return () => observer.disconnect();
  }, [hasReachedBottom, onScrolledToBottom]);

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle>Terms and Conditions</CardTitle>
          {hasReachedBottom && (
            <div className="flex items-center gap-2 text-sm text-green-600">
              <CheckCircle2 className="h-4 w-4" />
              <span>Scrolled to bottom</span>
            </div>
          )}
        </div>
        <p className="text-sm text-muted-foreground">
          Please scroll through and read all terms carefully before signing
        </p>
      </CardHeader>
      <CardContent>
        <div 
          ref={contentRef}
          className="max-h-[400px] overflow-y-auto border rounded-lg p-6 space-y-4 prose prose-sm max-w-none"
        >
          <h3 className="text-lg font-semibold">CARBON RIGHT CESSIONARY AGREEMENT</h3>
          
          <section>
            <p className="font-semibold">AGREEMENT</p>
            <p>
              MADE AND ENTERED INTO BY AND BETWEEN:
            </p>
            <p className="ml-4">
              <span className="font-semibold">[OWNER NAME]</span>, with registration number <span className="font-semibold">[REGISTRATION NUMBER]</span>, 
              whose registered office is at <span className="font-semibold">[REGISTERED OFFICE ADDRESS]</span> ("the <span className="font-semibold">Owner</span>");
            </p>
            <p>AND</p>
            <p className="ml-4">
              <span className="font-semibold">CRUNCH CARBON (PTY) LTD</span>, with registration number 2024/344308/07, 
              whose registered office is at Building 6, The Oval Office, 1 Oakdale Road, Newlands, 7700 ("the <span className="font-semibold">Cessionary</span>").
            </p>
            <p className="mt-4">
              The Owner and the Cessionary shall be referred to individually as a "Party" and collectively as "the Parties".
            </p>
          </section>

          <section>
            <h4 className="font-semibold">BACKGROUND</h4>
            <ol className="list-[upper-alpha] ml-6 space-y-2">
              <li>The Owner is the owner of a self-generation solar PV system ("the <span className="font-semibold">Premises</span>") located at: <span className="font-semibold">[PREMISES ADDRESS]</span>;</li>
              <li>The Owner owns certain solar photovoltaic systems ("the <span className="font-semibold">Installation</span>") erected on the Premises;</li>
              <li>The Installation enables the Owner to self-generate electrical energy on the Premises ("the <span className="font-semibold">Energy</span>");</li>
              <li>The Energy generated by the Installation results in the Owner earning carbon offset credits for the reduced carbon emissions ("the <span className="font-semibold">Carbon Credits</span>");</li>
              <li>The Owner is registered with the Department of Minerals and Energy of the Republic of South Africa ("the <span className="font-semibold">Department</span>") as a self-generator of Energy and is bound to report all Energy generated in terms of the Electricity Regulation Act, 2006;</li>
              <li>The Owner wishes to cede the Carbon Credits earned on the Premises to the Cessionary in order to monetize the Carbon Credits, and the Cessionary is agreeable to accepting the cession of the Carbon Credits on the terms and conditions set out in this agreement.</li>
            </ol>
          </section>

          <section>
            <h4 className="font-semibold">INTRODUCTION TO THE PARTIES</h4>
            <p>
              The introduction by the Parties immediately preceding this clause forms part of this agreement.
            </p>
          </section>

          <section>
            <h4 className="font-semibold">1. DEFINITIONS</h4>
            <p className="mb-2">In this agreement, unless the context indicates otherwise –</p>
            <dl className="ml-6 space-y-2">
              <dt className="font-semibold">"Business Day"</dt>
              <dd className="ml-4">means any day other than a Saturday, Sunday or gazetted public holiday in the Republic of South Africa;</dd>
              
              <dt className="font-semibold">"Carbon Credits"</dt>
              <dd className="ml-4">means all carbon credits which may accrue to the Owner in respect of, or as a result of, the use of the Installation on the Premises, and shall include, without limitation, all rights, benefits, claims of whatsoever nature or description in relation to the use of the Installation on the Premises and shall include, without limitation, all carbon credits, renewable energy credits, carbon offset credits, certified emission reduction credits and carbon offset certificates;</dd>
              
              <dt className="font-semibold">"Commencement Date"</dt>
              <dd className="ml-4">has the meaning given to it in clause 4.1 of this agreement;</dd>
              
              <dt className="font-semibold">"Cessionary"</dt>
              <dd className="ml-4">has the meaning given to it in the introduction to this agreement;</dd>
              
              <dt className="font-semibold">"Effective Date"</dt>
              <dd className="ml-4">means the date of the last of the Parties to sign this agreement;</dd>
              
              <dt className="font-semibold">"Energy"</dt>
              <dd className="ml-4">has the meaning given to it in the introduction to this agreement;</dd>
              
              <dt className="font-semibold">"Installation"</dt>
              <dd className="ml-4">has the meaning given to it in the introduction to this agreement;</dd>
              
              <dt className="font-semibold">"Installation Date"</dt>
              <dd className="ml-4">means the date the installation was installed on the Premises, and shall be deemed to be <span className="font-semibold">[INSTALLATION DATE]</span>;</dd>
              
              <dt className="font-semibold">"Law/s"</dt>
              <dd className="ml-4">shall mean all applicable laws, regulations, by-laws, rules, sub-rules, ordinances, promulgations and any amendments or re-enactments thereof or replacements therefor in force from time to time in the Republic of South Africa;</dd>
              
              <dt className="font-semibold">"Owner"</dt>
              <dd className="ml-4">has the meaning given to it in the introduction to this agreement;</dd>
              
              <dt className="font-semibold">"Premises"</dt>
              <dd className="ml-4">has the meaning given to it in the introduction to this agreement;</dd>
              
              <dt className="font-semibold">"Shares"</dt>
              <dd className="ml-4">has the meaning given to it in clause 8.2.2 of this agreement.</dd>
            </dl>
          </section>

          <section>
            <h4 className="font-semibold">2. INTERPRETATION</h4>
            <ol className="list-decimal ml-6 space-y-2">
              <li>Unless otherwise defined herein, terms defined in the Companies Act shall bear the same meaning in this agreement.</li>
              <li>Reference to any statutory enactment shall be construed as a reference to that enactment as at the Signature Date and as amended or substituted from time to time.</li>
              <li>Words importing the singular shall include the plural and vice versa, and words importing any gender shall include the other genders.</li>
              <li>Expressions defined in this agreement shall bear the same meaning throughout this agreement and any annexure/s or other document/s incorporated into the agreement.</li>
              <li>The clause headings have been inserted for convenience only and shall not be taken into account in the interpretation of this agreement.</li>
              <li>Where figures are referred to in numerals and in words, and there is any conflict between the two, the words shall prevail, unless the context indicates a contrary intention.</li>
              <li>Where any number of days is to be calculated from a particular date, such number shall be calculated exclusively of such date.</li>
              <li>If any provision in a definition is a substantive provision conferring a right or imposing an obligation on any Party, then, notwithstanding that it is only in the definition clause, effect shall be given to it as if it were a substantive provision in the body of the agreement.</li>
              <li>Any reference to an enactment is to that enactment as at the Signature Date and as amended or re-enacted from time to time.</li>
              <li>A reference to a day, other than a Business Day, is to be interpreted as that specific day.</li>
              <li>Reference to any agreement or contract shall include such agreement or contract, as amended from time to time.</li>
            </ol>
          </section>

          <section>
            <h4 className="font-semibold">3. REPRESENTATIONS AND WARRANTIES</h4>
            <p className="mb-2">Each Party represents and warrants to the other Party that –</p>
            <ol className="list-decimal ml-6 space-y-2">
              <li>it has been duly incorporated and validly exists, is in good standing and is registered in terms of all Laws of the Republic of South Africa;</li>
              <li>the person signing this agreement for and on behalf of that Party is duly authorised to enter into and bind that Party to this agreement; and</li>
              <li>it has the capacity and authority to enter into and to fulfil its obligations under this agreement.</li>
            </ol>
            <p className="mt-2">
              The Owner further represents and warrants that it has the full and unfettered right to cede the Carbon Credits to the Cessionary, and that the Carbon Credits are free of any liens, encumbrances or other security interests.
            </p>
          </section>

          <section>
            <h4 className="font-semibold">4. COMMENCEMENT AND DURATION</h4>
            <ol className="list-decimal ml-6 space-y-2">
              <li>This agreement shall come into operation on the Installation Date ("the <span className="font-semibold">Commencement Date</span>").</li>
              <li>Notwithstanding clause 4.1 above, the Parties acknowledge that this agreement shall only come into force on the Effective Date and that, accordingly, the provisions of this agreement shall apply with retrospective effect to the Commencement Date.</li>
              <li>This agreement shall endure for the duration of the estimated life expectancy of the Installation, which the Parties agree shall be deemed to be a period of 25 (twenty five) years, unless terminated earlier in accordance with the provisions of this agreement.</li>
            </ol>
          </section>

          <section>
            <h4 className="font-semibold">5. CESSION OF THE CARBON CREDITS</h4>
            <ol className="list-decimal ml-6 space-y-2">
              <li>The Owner hereby cedes, assigns and makes over to the Cessionary all of its right, title and interest in and to the Carbon Credits.</li>
              <li>The cession of the Carbon Credits contemplated in terms of clause 5.1 above is made in full and final settlement of all amounts due and owing by the Owner to the Cessionary under this agreement.</li>
              <li>The Owner shall sign all such documents and do such further acts and things as may be required by the Cessionary in order to give effect to the cession contemplated by this clause 5.</li>
              <li>The Owner undertakes to furnish the Cessionary with such records and information relating to the Energy and/or the Carbon Credits as the Cessionary may reasonably require from time to time.</li>
            </ol>
          </section>

          <section>
            <h4 className="font-semibold">6. ACCESS TO THE INSTALLATION</h4>
            <p className="mb-2">
              The Owner hereby grants the Cessionary, and any person duly authorised by the Cessionary, the right of access to the Premises to inspect and test the Installation at all reasonable times, provided that –
            </p>
            <ol className="list-decimal ml-6 space-y-2">
              <li>the Cessionary provides the Owner with at least 48 (forty eight) hours' prior written notice of its intention to access the Premises; and</li>
              <li>the Cessionary complies with all reasonable safety and security measures required by the Owner when accessing the Premises.</li>
            </ol>
          </section>

          <section>
            <h4 className="font-semibold">7. MAINTENANCE OF THE INSTALLATION</h4>
            <p>
              The Owner undertakes to maintain the Installation in good working order and condition and to ensure that the Installation complies with all applicable Laws and safety standards.
            </p>
          </section>

          <section>
            <h4 className="font-semibold">8. FINANCIAL PROVISIONS</h4>
            <ol className="list-decimal ml-6 space-y-2">
              <li>
                <span className="font-semibold">Sale of the Carbon Credits</span>
                <ol className="list-[decimal] ml-6 mt-1 space-y-1">
                  <li>The Cessionary shall be solely responsible for the sale of the Carbon Credits and shall be entitled to sell the Carbon Credits at such times and on such terms as it deems fit.</li>
                  <li>The Cessionary shall not be obliged to sell the Carbon Credits at any particular time or for any particular price.</li>
                </ol>
              </li>
              <li>
                <span className="font-semibold">Distribution of the proceeds</span>
                <ol className="list-[decimal] ml-6 mt-1 space-y-1">
                  <li>The Cessionary shall distribute the proceeds of the sale of the Carbon Credits between itself and the Owner in the following proportions ("the <span className="font-semibold">Shares</span>"):
                    <ul className="list-disc ml-6 mt-1">
                      <li>the Cessionary shall be entitled to [CESSIONARY PERCENTAGE]% of the proceeds; and</li>
                      <li>the Owner shall be entitled to [OWNER PERCENTAGE]% of the proceeds.</li>
                    </ul>
                  </li>
                  <li>The Cessionary shall pay the Owner's Share to the Owner within 30 (thirty) days of receipt of the proceeds of the sale of the Carbon Credits.</li>
                  <li>All payments shall be made by electronic funds transfer into the following bank account of the Owner:
                    <ul className="list-none ml-6 mt-1">
                      <li>Account holder: [ACCOUNT HOLDER NAME]</li>
                      <li>Bank: [BANK NAME]</li>
                      <li>Account number: [ACCOUNT NUMBER]</li>
                      <li>Branch code: [BRANCH CODE]</li>
                    </ul>
                  </li>
                </ol>
              </li>
            </ol>
          </section>

          <section>
            <h4 className="font-semibold">9. RECORDS AND REPORTING</h4>
            <p className="mb-2">The Cessionary shall –</p>
            <ol className="list-decimal ml-6 space-y-2">
              <li>keep proper records of all sales of the Carbon Credits and of the distribution of the proceeds thereof; and</li>
              <li>provide the Owner with a written statement setting out the details of all sales of the Carbon Credits and the distribution of the proceeds thereof within 30 (thirty) days of the end of each financial year of the Cessionary.</li>
            </ol>
          </section>

          <section>
            <h4 className="font-semibold">10. WARRANTIES</h4>
            <p className="mb-2">The Cessionary does not warrant or make any representations to the Owner in respect of –</p>
            <ol className="list-decimal ml-6 space-y-2">
              <li>the value of the Carbon Credits;</li>
              <li>the ability of the Cessionary to sell the Carbon Credits; or</li>
              <li>the price at which the Cessionary will be able to sell the Carbon Credits.</li>
            </ol>
          </section>

          <section>
            <h4 className="font-semibold">11. INDEMNITY</h4>
            <ol className="list-decimal ml-6 space-y-2">
              <li>The Owner hereby indemnifies and holds harmless the Cessionary against all actions, claims, demands, losses, liabilities, costs and expenses of whatsoever nature which the Cessionary may suffer or incur as a result of any breach by the Owner of any of the provisions of this agreement.</li>
              <li>The indemnity contained in clause 11.1 above shall survive the termination of this agreement.</li>
            </ol>
          </section>

          <section>
            <h4 className="font-semibold">12. CONFIDENTIALITY</h4>
            <ol className="list-decimal ml-6 space-y-2">
              <li>Each Party undertakes to keep confidential all information disclosed to it by the other Party in connection with this agreement, and not to disclose such information to any third party without the prior written consent of the disclosing Party.</li>
              <li>The provisions of clause 12.1 above shall not apply to information which:
                <ol className="list-[decimal] ml-6 mt-1 space-y-1">
                  <li>is or becomes publicly available otherwise than through a breach of this agreement;</li>
                  <li>is required to be disclosed by Law or by any regulatory authority; or</li>
                  <li>is already in the possession of the receiving Party at the time of disclosure.</li>
                </ol>
              </li>
            </ol>
          </section>

          <section>
            <h4 className="font-semibold">13. TERMINATION</h4>
            <ol className="list-decimal ml-6 space-y-2">
              <li>
                <span className="font-semibold">Termination by the Cessionary</span>
                <p className="ml-6 mt-1">
                  The Cessionary may terminate this agreement by giving the Owner not less than 90 (ninety) days' written notice.
                </p>
              </li>
              <li>
                <span className="font-semibold">Termination by the Owner</span>
                <p className="ml-6 mt-1">
                  The Owner may terminate this agreement by giving the Cessionary not less than 90 (ninety) days' written notice, provided that the Owner pays to the Cessionary an early termination fee equal to [TERMINATION FEE AMOUNT] (the "<span className="font-semibold">Early Termination Fee</span>").
                </p>
              </li>
              <li>
                <span className="font-semibold">Termination for breach</span>
                <p className="ml-6 mt-1">
                  Either Party may terminate this agreement immediately by written notice to the other Party if the other Party commits a material breach of any of the provisions of this agreement and fails to remedy such breach within 30 (thirty) days of receipt of written notice requiring it to do so.
                </p>
              </li>
              <li>
                <span className="font-semibold">Effect of termination</span>
                <ol className="list-[decimal] ml-6 mt-1 space-y-1">
                  <li>Upon termination of this agreement, the Cessionary shall be entitled to retain all Carbon Credits which have been ceded to it up to the date of termination.</li>
                  <li>The Cessionary shall, within 60 (sixty) days of the date of termination, account to the Owner for all proceeds of the sale of the Carbon Credits which have been received by the Cessionary up to the date of termination and which have not yet been distributed to the Owner in accordance with clause 8.2 above.</li>
                </ol>
              </li>
            </ol>
          </section>

          <section>
            <h4 className="font-semibold">14. BREACH</h4>
            <p className="mb-2">
              Save as otherwise expressly provided in this agreement, any breach of a material term of this agreement by either Party which is not capable of being remedied, or if capable of being remedied, is not remedied within 30 (thirty) Business Days from the date upon which the Party in breach receives written notice from the other Party calling upon it to remedy the breach, shall entitle the other Party (the "aggrieved Party"), without prejudice to any other rights it may have in terms of this agreement or in law, to –
            </p>
            <ol className="list-decimal ml-6 space-y-2">
              <li>claim immediate specific performance of all of the other Party's obligations, whether or not the due date for performance has arrived;</li>
              <li>cancel this agreement and claim damages; or</li>
              <li>claim damages without cancelling this agreement.</li>
            </ol>
          </section>

          <section>
            <h4 className="font-semibold">15. FORCE MAJEURE</h4>
            <ol className="list-decimal ml-6 space-y-2">
              <li>Neither Party shall be liable for any delay or failure in the performance of any of its obligations under this agreement if such delay or failure is caused by circumstances beyond its reasonable control, including but not limited to acts of God, war, civil commotion, strikes, lockouts, acts of government or any other force majeure event ("a <span className="font-semibold">Force Majeure Event</span>").</li>
              <li>If a Force Majeure Event occurs, the Party affected thereby shall notify the other Party in writing as soon as reasonably practicable and shall use all reasonable endeavours to minimise the effect of the Force Majeure Event.</li>
              <li>If a Force Majeure Event continues for more than 90 (ninety) days, either Party may terminate this agreement by giving written notice to the other Party.</li>
            </ol>
          </section>

          <section>
            <h4 className="font-semibold">16. NOTICES AND DOMICILIUM</h4>
            <ol className="list-decimal ml-6 space-y-2">
              <li>
                <span className="font-semibold">Domicilium</span>
                <p className="ml-6 mt-1 mb-1">
                  The Parties choose as their domicilium citandi et executandi for all purposes under this agreement, whether in respect of court process, notices, or other documents or communications of whatsoever nature, the following addresses –
                </p>
                <div className="ml-6 space-y-2">
                  <div>
                    <p className="font-semibold">Owner:</p>
                    <p className="ml-4">Physical address: [OWNER PHYSICAL ADDRESS]</p>
                    <p className="ml-4">Email address: [OWNER EMAIL]</p>
                  </div>
                  <div>
                    <p className="font-semibold">Cessionary:</p>
                    <p className="ml-4">Physical address: Building 6, The Oval Office, 1 Oakdale Road, Newlands, 7700</p>
                    <p className="ml-4">Email address: info@crunchcarbon.com</p>
                  </div>
                </div>
              </li>
              <li>
                <span className="font-semibold">Method of service</span>
                <ol className="list-[decimal] ml-6 mt-1 space-y-1">
                  <li>Any notice or communication required or permitted to be given in terms of this agreement shall be valid and effective only if in writing.</li>
                  <li>Any Party may by notice to the other Party change the physical address or email address chosen as its domicilium citandi et executandi to another physical address or email address, provided that the change shall become effective on the 10th (tenth) Business Day from the receipt of the notice by the addressee.</li>
                  <li>Any notice to a Party:
                    <ol className="list-[lower-alpha] ml-6 mt-1 space-y-1">
                      <li>sent by prepaid registered post (by airmail if appropriate) in a correctly addressed envelope to it at its chosen domicilium citandi et executandi shall be deemed to have been received on the 10th (tenth) Business Day after posting (unless the contrary is proved);</li>
                      <li>delivered by hand to a responsible person during ordinary business hours at the physical address chosen as its domicilium citandi et executandi shall be deemed to have been received on the day of delivery;</li>
                      <li>sent by email to its chosen email address shall be deemed to have been received on the date of dispatch.</li>
                    </ol>
                  </li>
                  <li>Notwithstanding anything to the contrary herein contained a written notice or communication actually received by a Party shall be an adequate written notice or communication to it notwithstanding that it was not sent to or delivered at its chosen domicilium citandi et executandi.</li>
                </ol>
              </li>
            </ol>
          </section>

          <section>
            <h4 className="font-semibold">17. GENERAL</h4>
            <ol className="list-decimal ml-6 space-y-2">
              <li>
                <span className="font-semibold">Governing law</span>
                <p className="ml-6 mt-1">
                  This agreement shall be governed by and construed in accordance with the laws of the Republic of South Africa.
                </p>
              </li>
              <li>
                <span className="font-semibold">Jurisdiction</span>
                <p className="ml-6 mt-1">
                  The Parties consent to the jurisdiction of the High Court of South Africa, Western Cape Division, Cape Town in respect of any disputes arising out of or in connection with this agreement.
                </p>
              </li>
              <li>
                <span className="font-semibold">Whole agreement</span>
                <p className="ml-6 mt-1">
                  This agreement constitutes the whole agreement between the Parties relating to the subject matter hereof and no agreements, representations or warranties between the Parties regarding the subject matter hereof other than those set out herein are binding on the Parties.
                </p>
              </li>
              <li>
                <span className="font-semibold">Variation</span>
                <p className="ml-6 mt-1">
                  No addition to, variation, or agreed cancellation of this agreement shall be of any force or effect unless in writing and signed by or on behalf of all the Parties.
                </p>
              </li>
              <li>
                <span className="font-semibold">No waiver</span>
                <p className="ml-6 mt-1">
                  No indulgence, leniency or extension of time which either Party ("the grantor") may show grant or allow to the other ("the grantee") shall in any way prejudice the grantor or preclude the grantor from exercising any of its rights in the future.
                </p>
              </li>
              <li>
                <span className="font-semibold">Severability</span>
                <p className="ml-6 mt-1">
                  If any provision of this agreement is found by any court of competent jurisdiction to be invalid or unenforceable, such invalidity or unenforceability shall not affect the other provisions of this agreement which shall remain in full force and effect.
                </p>
              </li>
              <li>
                <span className="font-semibold">Costs</span>
                <p className="ml-6 mt-1">
                  Each Party shall bear its own costs in relation to the negotiation, preparation and implementation of this agreement.
                </p>
              </li>
              <li>
                <span className="font-semibold">Counterparts</span>
                <p className="ml-6 mt-1">
                  This agreement may be executed in any number of counterparts, each of which shall be deemed an original, but all of which together shall constitute one and the same instrument.
                </p>
              </li>
            </ol>
          </section>

          <section>
            <h4 className="font-semibold">18. DISPUTE RESOLUTION</h4>
            <ol className="list-decimal ml-6 space-y-2">
              <li>If a dispute arises between the Parties in connection with this agreement, the Parties shall first attempt to resolve the dispute by way of negotiations between senior management representatives of each Party.</li>
              <li>If the dispute is not resolved by negotiation within 30 (thirty) days of the dispute arising, either Party may refer the dispute to arbitration in accordance with the rules of the Arbitration Foundation of Southern Africa.</li>
              <li>The arbitration shall be conducted by a single arbitrator appointed by agreement between the Parties, or failing agreement within 10 (ten) Business Days of the referral to arbitration, by the Arbitration Foundation of Southern Africa.</li>
              <li>The decision of the arbitrator shall be final and binding on the Parties.</li>
              <li>Each Party shall bear its own costs of the arbitration, and the Parties shall share equally the costs of the arbitrator.</li>
            </ol>
          </section>

          <section>
            <h4 className="font-semibold">19. ELECTRONIC SIGNATURE</h4>
            <p>
              The Parties agree that this agreement may be signed electronically and that an electronic signature shall have the same legal effect as a handwritten signature. By typing your name and submitting this agreement electronically, you acknowledge that your electronic signature is legally binding and that you agree to be bound by all terms and conditions set forth in this agreement.
            </p>
          </section>

          <div ref={sentinelRef} className="h-1" />
        </div>
      </CardContent>
    </Card>
  );
}
