import { useEffect, useRef, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { CheckCircle2 } from "lucide-react";

interface TermsAndConditionsSectionProps {
  onScrolledToBottom: () => void;
}

export function TermsAndConditionsSection({ onScrolledToBottom }: TermsAndConditionsSectionProps) {
  const [hasReachedBottom, setHasReachedBottom] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);
  const sentinelRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting && !hasReachedBottom) {
          setHasReachedBottom(true);
          onScrolledToBottom();
        }
      },
      { threshold: 1.0 }
    );

    if (sentinelRef.current) {
      observer.observe(sentinelRef.current);
    }

    return () => observer.disconnect();
  }, [hasReachedBottom, onScrolledToBottom]);

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle>Terms and Conditions</CardTitle>
          {hasReachedBottom && (
            <div className="flex items-center gap-2 text-sm text-green-600">
              <CheckCircle2 className="h-4 w-4" />
              <span>Scrolled to bottom</span>
            </div>
          )}
        </div>
        <p className="text-sm text-muted-foreground">
          Please scroll through and read all terms carefully before signing
        </p>
      </CardHeader>
      <CardContent>
        <div 
          ref={contentRef}
          className="max-h-[400px] overflow-y-auto border rounded-lg p-6 space-y-4 prose prose-sm max-w-none"
        >
          <h3 className="text-lg font-semibold">Carbon Credit Proposal Agreement</h3>
          
          <section>
            <h4 className="font-semibold">1. Parties to the Agreement</h4>
            <p>
              This agreement is entered into between the Client (as identified in the proposal) and 
              Crunch Carbon (the "Service Provider"), collectively referred to as "the Parties."
            </p>
          </section>

          <section>
            <h4 className="font-semibold">2. Scope of Services</h4>
            <p>
              The Service Provider agrees to facilitate the registration, verification, and monetization 
              of carbon credits generated by the Client's solar energy system as described in this proposal.
            </p>
          </section>

          <section>
            <h4 className="font-semibold">3. Revenue Sharing</h4>
            <p>
              The revenue generated from carbon credits will be distributed according to the percentages 
              specified in the proposal summary. The Client's share represents their portion of the total 
              carbon credit revenue after accounting for administrative costs and commissions.
            </p>
          </section>

          <section>
            <h4 className="font-semibold">4. Duration and Termination</h4>
            <p>
              This agreement shall remain in effect for the duration of the carbon credit generation period, 
              typically aligned with the operational life of the solar system. Either party may terminate 
              this agreement with 90 days written notice.
            </p>
          </section>

          <section>
            <h4 className="font-semibold">5. Data and Documentation</h4>
            <p>
              The Client agrees to provide accurate and timely data regarding energy generation, system 
              specifications, and other information necessary for carbon credit verification and registration.
            </p>
          </section>

          <section>
            <h4 className="font-semibold">6. Payment Terms</h4>
            <p>
              Payments will be made quarterly following the successful sale of carbon credits. The Service 
              Provider will provide detailed statements of all transactions and distributions.
            </p>
          </section>

          <section>
            <h4 className="font-semibold">7. Compliance and Regulatory Changes</h4>
            <p>
              Both parties agree to comply with all applicable laws, regulations, and carbon credit standards. 
              In the event of regulatory changes that materially affect this agreement, the Parties agree to 
              renegotiate terms in good faith.
            </p>
          </section>

          <section>
            <h4 className="font-semibold">8. Representations and Warranties</h4>
            <p>
              The Client represents that they have legal authority to enter into this agreement and that 
              the information provided regarding the solar system is accurate and complete.
            </p>
          </section>

          <section>
            <h4 className="font-semibold">9. Limitation of Liability</h4>
            <p>
              Neither party shall be liable for indirect, incidental, or consequential damages arising from 
              this agreement. The Service Provider's liability is limited to the fees paid under this agreement.
            </p>
          </section>

          <section>
            <h4 className="font-semibold">10. Dispute Resolution</h4>
            <p>
              Any disputes arising from this agreement shall first be addressed through good faith negotiations. 
              If unresolved, disputes shall be settled through binding arbitration in accordance with the rules 
              of the American Arbitration Association.
            </p>
          </section>

          <section>
            <h4 className="font-semibold">11. Electronic Signature</h4>
            <p>
              By typing your name and submitting this agreement electronically, you acknowledge that your 
              electronic signature has the same legal effect as a handwritten signature and that you agree 
              to be bound by all terms and conditions set forth in this proposal.
            </p>
          </section>

          <section>
            <h4 className="font-semibold">12. Entire Agreement</h4>
            <p>
              This agreement, including the proposal details, constitutes the entire agreement between the 
              Parties and supersedes all prior negotiations, representations, or agreements relating to the 
              subject matter herein.
            </p>
          </section>

          <div ref={sentinelRef} className="h-1" />
        </div>
      </CardContent>
    </Card>
  );
}
